### ISSUE TITLE
empirical-cdf support

### ISSUE THREAD

**Issue by ronniec95** [boxtown/statrs#107]
Math.NET.Statistics.* has support for sampling data and calculating e-cdf, quantiles and so on. Is there a chance that you'll extend your feature matching to those

**Comment by boxtown** [comment]
I've been pretty busy with work so haven't really planned out any new features but always open to feature requests. If you have a couple high priority requests I'd be happy to take a look at porting some of that functionality over in my spare time

**Comment by troublescooter** [comment]
A bare-bones empirical distribution was implemented in #120 , and quantiles should also work, although it could do with more testing.
