### ISSUE TITLE
Implementation of inverse digamma

### ISSUE THREAD

**Issue by boxtown** [boxtown/statrs#11]
Need resources on good implementation of inverse digamma (psi) function. The Math.NET code seems to be incorrect and doesn't even pass their own unit tests

**Comment by vks** [comment]
[This paper](http://research.microsoft.com/en-us/um/people/minka/papers/dirichlet/) describes an implementation using Newton's method in Appendix C.

**Comment by boxtown** [comment]
Appreciate it @vks ! I'll look into it when I get the chance

**Comment by boxtown** [comment]
implemented
