### ISSUE TITLE
PPF functions in particular for Student's T

### ISSUE THREAD

**Issue by willir** [boxtown/statrs#112]
Hi, are there any plans for implementing the Percent Point Function (a.k.a. quantile)?

**Comment by willir** [comment]
Oh, you have `InverseCDF`, it just isn't implemented for all distributions. For example it isn't implemented for Student's T. So the function is planned.

If I find time to implement it for Student's T, would it be a welcome merge request?

**Comment by troublescooter** [comment]
Since there's no nice form of the inverse in general yet one would want quantiles for all implemented distributions, it would perhaps make sense to merge `InverseCDF` into `Univariate`.
A default implementation could then be given that uses binary search on the domain to approximate `inf x : F(x) >= a`.

**Comment by willir** [comment]
Well, having a default implementation might be a good idea for distributions that do not have a nice form of the inverse.

CDF is a non-decreasing function, so the binary search should work. Though I'm not that good at math and I'm not aware of all corner cases that might prevent binary search implementation.

We, though, would have to change the declaration of `Univariate` trait, currently, it only requires `Min`, `Max`. We would need a comparison. And since we to stop at some epsilon, the comparison must be made with regard to some epsilon.

On the other hand, if some distributions don't "support" inverse, it might be reasonable to leave `cdf` and `ppf` (`inverse_cdf`) in separate traits, so it is more clear where it is really implemented.

In the meantime, I think I will try to implement `inverse_cdf` for `StudentsT` based on the [C++ boost implementation](https://github.com/boostorg/math/blob/develop/include/boost/math/distributions/students_t.hpp#L207).

**Comment by troublescooter** [comment]
A default implementation of the inverse cdf has been provided with #120 .
