### ISSUE TITLE
Test coverage for Statistic.rank for n > 10

### ISSUE THREAD

**Issue by boxtown** [boxtown/statrs#13]
Need code coverage on case where data length > 10 for rank function in order to cover the quick_sort impl. As a side note, the quick sort impl is borrowed whole sale from Math.NET and there is probably a more idiomatic Rust implementation that could be used.

**Comment by vks** [comment]
Why not use `std::sort`?

**Comment by boxtown** [comment]
got a link to the docs? I wasn't able to find anything. Also, `rank` needs to be able to determine sort order of ties as well

**Comment by vks** [comment]
Sorting is implemented for [slices](https://doc.rust-lang.org/std/primitive.slice.html): [`sort`](https://doc.rust-lang.org/std/primitive.slice.html#method.sort), [`sort_by`](https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by), [`sort_by_key`](https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by_key).

**Comment by boxtown** [comment]
I don't think the standard sorts can be used since `rank` is not necessarily a stable sort depending on the tie-breaker method chosen

**Comment by troublescooter** [comment]
Fixed in #109
