### ISSUE TITLE
README out of date

### ISSUE THREAD

**Issue by reknih** [boxtown/statrs#135]
The first example in the README is outdated.

- The `rand` crate's [`StdRng`](https://docs.rs/rand/0.8.3/rand/rngs/struct.StdRng.html) does no longer have a `new` constructor. Consider using `from_entropy` or `from_seed` instead.
- Starting at version 0.1.0, `statrs` does no longer include a `Distribution` trait and instead relies on [`rand`s `Distribution`](https://docs.rs/rand/0.8.3/rand/distributions/trait.Distribution.html).

I did not try the other examples yet, but I think it would be great to fix this since the Readme (exp. when viewed on crates.io) is the first point of contact with the crate for many users. Thankfully, the documentation on docs.rs is up-to-date and very useful! Also consider removing the instruction to add the `extern crate statrs` line in the Usage section since most users should be on Rust's 2018 edition by now.

**Comment by nblei** [comment]
Agreed.

Trying to use rand and statsr is a nightmare of changing APIs and out-of-date documentation for a newcomer.

**Comment by troublescooter** [comment]
> Trying to use rand and statsr is a nightmare of changing APIs and out-of-date documentation for a newcomer.
> It shouldn't take multiple trips to doc.rs and github to figure out how to sample a binomial distribution.

We recommend opening an issue if something is confusing. Occasionally things get lost.

Thanks for the report, I've updated the README to match current git.
