### ISSUE TITLE
Review of iterator statistics trait

### ISSUE THREAD

**Issue by boxtown** [boxtown/statrs#18]
Currently the iterator statistics trait is treated as a special case since to act over the iterator the methods need to take a mutable reference, so all the traits from `statrs::statistics` are (going to be) combined in the `IterStatistics` trait that is implemented for all Iterators. I haven't come up with a better solution but for some reason this implementation doesn't sit too well with me and I'd love to have someone review it and provide feedback.

**Comment by vks** [comment]
So you want to implement some methods on iterators? I don't really see any alternative to something like `IterStatistics`. Do you not like the `T::Item: Borrow<f64>` bound?

**Comment by boxtown** [comment]
It's more about the fact that I have to create a complete separate trait for iterators but like you said, I can't really see any alternative at the moment

**Comment by vks** [comment]
So you would prefer to implement `Min`, `Mean` etc. directly on iterators? This would require changing the signature of those traits to allow consuming/mutating `self`, which is more general.

**Comment by boxtown** [comment]
Yeah it's kind of being caught between a rock and a hard place. On one hand, I don't want to duplicate the functionality of those traits inside `IterStatistics`, but on the other hand for the general case `&self` is a better match for those traits than `&mut self` which is unnecessarily restrictive

**Comment by vks** [comment]
Did you try `IntoIterator`?

```rust
use std::f64;

trait AbsMin<T> {
    fn abs_min(self) -> T;
}

impl<'a, T> AbsMin<f64> for T
    where T: IntoIterator<Item=&'a f64>,
          T::IntoIter: Iterator<Item=&'a f64>
{
    fn abs_min(self) -> f64 {
        let mut it = self.into_iter();
        match it.next() {
            None => f64::NAN,
            Some(init) => {
                it.map(|x| x.abs())
                  .fold(init.abs(),
                        |acc, x| if x < acc || x.is_nan() { x } else { acc })
            }
        }
    }
}

fn main() {
    let a = [1., 2., 3.];
    let it = a.iter();
    println!("{}", it.abs_min());
    println!("{}", a.abs_min());
}
```

(Probably should be extended so it works for `Iterator<Item=f64>` and `Iterator<Item=&mut f64>`.)

**Comment by boxtown** [comment]
Yeah I tried that path but the issue is that I want to support the trait for `&[f64]` which precludes me from being able to define a trait that requires ownership (e.g. `self` vs &self`). I might be missing something though

**Comment by vks** [comment]
My implementation works for `&[64]`! (Note that slices implement `Copy`, so it is no problem to consume them to turn them into an iterator.)

**Comment by boxtown** [comment]
This looks promising. The one hiccup ties into #13  where the sort and selection algorithms are unique for slices in that they operate in-place. It doesn't sit well with me to have a slice turned into an iterator than collected back into a slice in order to perform the in place algorithms. Thoughts?

**Comment by vks** [comment]
I don't think sort should be defined for iterators, it should only be defined for slices, like in std. This applies for other in-place algorithms as well.

**Comment by boxtown** [comment]
Hmm so are you suggesting methods like `rank`, `order`, `quantile`, `percentile`, etc (everything belonging to `InplaceStatistics`) be only defined on slices? That could definitely be a possibility

**Comment by vks** [comment]
I don't think it makes sense to define them on iterators if they have to collect everything into a vector anyway. Defining them on slices is nicer, because then the user can decide which storage to use (a possibly preallocated `Vec` on the heap or an array on the stack), and it makes it possible to use them without any allocation.

For methods like `mean` and `variance` iterators make sense, because only one element at a time is required. With `IntoIterator` it will work for slices as well.

**Comment by boxtown** [comment]
Have had some success generalizing the trait by using `IntoIterator` (see [here](https://github.com/boxtown/statrs/tree/generalize_stat_traits)). The issue I'm running into is that to implement the other more generic traits (e.g. `Mean`, `Min`, `Max`, etc) would require a change to their signature from `&self` to `self`, forcing me to make duplicate implementations for `&Impl` and `&mut Impl` for all the distributions. One option would be to forgo the use of the generalized traits and have that functionality duplicated in `Statistics` but that doesn't sit too well with me. Thoughts?

**Comment by vks** [comment]
Doesn't the signature have to be `self`, because you are consuming the iterator? Where exactly does that result in duplication?

**Comment by boxtown** [comment]
Right the trait signature has to be `self`, which means for the other implementors (i.e. all the Distributions that implement `Min`, `Max`, `Mean`, etc) you have to do an implementation for the immutable AND mutable reference:

```
trait Mean<T> {
  fn mean(self) ->T;
}

struct Normal{mean: f64, std_dev: f64}

impl Mean<f64> for &'a Normal {
  fn mean(self) -> f64 {
    self.mean
  }
}

impl Mean<f64> for &'a mut Normal {
  fn mean(self) -> f64 {
    self.mean
  }
}
```

**Comment by vks** [comment]
Do you really need traits for the distributions? Couldn't you just define
the method directly on the type? This would be similar to what the standard
library is doing.

**Comment by boxtown** [comment]
Obviously the traits are not a technical impediment, I could eschew them and just implement methods directly on the distributions. However, I think the traits really play to a strong suit of Rust that allows us to explicitly define the behavior of distributions and distribution classes and it's something I'd like to keep in the library. I may see if writing a macro to generate implementations for mutable and immutable references might be a feasibly approach

**Comment by vks** [comment]
The problem is that it will only work for references to distributions, not
for actual values.

**Comment by boxtown** [comment]
Right and that's really the heart of the trait problem. Either we sacrifice on the distribution implementation side or on a unified trait for iterable statistics. I'm leaning towards just having a separate trait for Iterators as a special case since the purpose of this package is originally to provide robust distribution implementations. Of course, if we ever get HKT I might be able to revisit this

**Comment by vks** [comment]
Yes, I agree that for now having a trait for iterators/slices and another
one for distributions seems like the best option.

**Comment by boxtown** [comment]
Slices and iterables now share the `Statistics` trait which has it's own implementations of `Min`, `Max`, `Mean`, and `Variance`. `[f64]` still implements the aforementioned traits by delegating to the `Statistics` implementation. See https://github.com/boxtown/statrs/commit/df0b1b2b8b23f9df4c0f6bb0a757daeeb07548bf
