### ISSUE TITLE
Implement Multinomial distribution

### ISSUE THREAD

**Issue by boxtown** [boxtown/statrs#46]
References:
https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/Distributions/Multinomial.cs
https://en.wikipedia.org/wiki/Multinomial_distribution

**Comment by vks** [comment]
I recently implemented exact multinomial coefficients in `num`.

**Comment by boxtown** [comment]
@vks Thanks, could I bother you to provide a link?

**Comment by vks** [comment]
Sure: https://github.com/rust-num/num/blob/master/integer/src/lib.rs

**Comment by boxtown** [comment]
Completed with b5bfc2c
