### ISSUE TITLE
Use dev-dependencies for random number generation

### ISSUE THREAD

**Issue by vks** [boxtown/statrs#51]
I just saw this in the code:

```rust
    #[ignore]
    #[test]
    fn test_mean_variance_stability() {
        // TODO: Implement tests. Depends on Mersenne Twister RNG implementation.
        // Currently hesistant to bring extra dependency just for test
    }
```

You can add dependencies to the Cargo.toml that are only used when running the tests, but not when using the library as a dependency: http://doc.crates.io/specifying-dependencies.html#development-dependencies

**Comment by boxtown** [comment]
@vks Thanks, I'll look to flesh out the test then in that case, hopefully in 0.7.0

**Comment by boxtown** [comment]
Punting to 0.8.0

**Comment by boxtown** [comment]
Punting to future release. I can't find a well supported stable implementation of the Mersenne Twister algo, it is likely that a home grown implementation will be needed. Reference: https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/Random/MersenneTwister.cs

**Comment by vks** [comment]
Why do you want to use the Mersenne Twister? It is a bit dated, there are faster algorithms with better statistics ([PCG](http://www.pcg-random.org/), [xoroshiro128+](http://xoroshiro.di.unimi.it/)).

**Comment by boxtown** [comment]
It's for a direct port of this test https://github.com/mathnet/mathnet-numerics/blob/master/src/UnitTests/StatisticsTests/StatisticsTests.cs#L817

I'm actually not sure if the Mersenne Twister is 100% necessary but I don't know enough about the stability issues this particular test is testing

**Comment by vks** [comment]
I would expect they use the Mersenne Twister because the default .NET random number generator has low quality and/or period? You are probably fine with just using `rand::IsaacRng` or `rand::IsaacRng64`.

**Comment by vks** [comment]
I would expect they use the Mersenne Twister because the default .NET random number generator has low quality and/or period? You are probably fine with just using `rand`.
