### ISSUE TITLE
Ensure uniform sample is in range [min, max]

### ISSUE THREAD

**Issue by boxtown** [boxtown/statrs#61]
See #60

**Comment by mp4096** [comment]
#60 fixed the upper bound. Now we have to ensure we have a closed-closed interval instead of closed-open.

There's a [`Closed01`](https://doc.rust-lang.org/rand/rand/struct.Closed01.html) wrapper in the `rand` crate. I'll take a look into it, maybe we can use it.

**Comment by mp4096** [comment]
I updated #60 to sample from a closed-closed range `[min, max]`.

**Comment by boxtown** [comment]
Resolved wit h 5d07c04. Thanks @mp4096
