### ISSUE TITLE
Testing for special functions

### ISSUE THREAD

**Issue by boxtown** [boxtown/statrs#7]
Special functions sorely in need of unit testing

**Comment by vks** [comment]
You could probably steal a few mpmath tests: See for instance [this](https://github.com/fredrik-johansson/mpmath/blob/master/mpmath/tests/test_functions2.py).

**Comment by boxtown** [comment]
@vks Thanks for the tip! I'll look into it for sure

**Comment by boxtown** [comment]
completed for 0.2.0 milestone, will open new issue to expand special functions for next mile stone
