### ISSUE TITLE
Add coverage testing

### ISSUE THREAD

**Issue by mp4096** [boxtown/statrs#72]
I want to make a PR for coverage testing. @boxtown Do you want to publish results to CodeCov or Coveralls?

* [CodeCov example](https://codecov.io/gh/postmates/cernan)
* [Coveralls example](https://coveralls.io/github/mp4096/indentex?branch=master)

**Comment by mp4096** [comment]
Here's how it looks like right now (Coveralls): https://coveralls.io/github/mp4096/statrs

**Comment by boxtown** [comment]
I'll need a little time to review the options, thanks!

**Comment by boxtown** [comment]
So I don't have a huge amount of experience with Coveralls or CodeCov but with the little bit of digging I did, I'm leaning towards CodeCov. Do you have any opinions one way or the other @mp4096

**Comment by mp4096** [comment]
Nope, I'm pretty neutral. I discovered Coveralls first and then just stayed with it. I do think CodeCov offers nicer UI, especially the sunburst plot.

CodeCov it be. @boxtown Could you please turn CodeCov for this repo on? Then I'll open a PR and we'll see how it looks like.

**Comment by boxtown** [comment]
CodeCov **should** be enabled, let me know if you are having any issues

**Comment by mp4096** [comment]
Check out #75! Also, https://codecov.io/gh/boxtown/statrs
