### ISSUE TITLE
Support for f32 

### ISSUE THREAD

**Issue by rohitjoshi** [boxtown/statrs#84]
For ML/Deep learning, it might be ok to use lower precision floating point numbers in many cases which will allow storing more data in memory. 

Also, see an interesting article  about [Eight-bit floating point](https://www.johndcook.com/blog/2018/04/15/eight-bit-floating-point/)

**Comment by boxtown** [comment]
There is already an issue open for this. I definitely have a desire to support multiple numeric types but as of my last attempt, the state of numeric traits in Rust wasn't at a place where the juice was worth the squeeze so to speak. I'd be happy to revisit if the situation has changed. For future comments though, please direct them to the #17
