### ISSUE TITLE
implement assert_almost_eq macro

### ISSUE THREAD

**Issue by boxtown** [boxtown/statrs#9]
Implement macro to short hand prec::almost_eq

**Comment by boxtown** [comment]
done

**Comment by vks** [comment]
I'm not sure that the currently implementation is what you want. The point of `assert_eq` over `assert` is that it shows the left-hand side and the right-hand side in case of failure. I don't think the current implementation of `assert_almost_eq` does that.

**Comment by boxtown** [comment]
Very good point. I will probably revise this tonight

**Comment by boxtown** [comment]
update implementation to be more informative
