### ISSUE TITLE
Update the dependency on rand

### ISSUE THREAD

**Issue by ManifoldFR** [boxtown/statrs#92]
There's a compatibility issue between the current version of `statrs`, which depends on `rand` 0.5 (so, up to 0.5.5), and the latest version of `rand` (0.6).

**Minimal example**

Using the `Cargo.toml` dependencies section
```toml
[dependencies]
statrs = "0.10.0"
rand = "0.6.3"
```
and trying to compile the `main.rs` file
```rust
use statrs::distribution::Normal;

use rand::Rng;
use rand::distributions::Distribution;

fn main() {
    let n = Normal::new(0., 0.).unwrap();
    let ref mut rng = rand::thread_rng();
    let v = n.sample(rng);
    println!("Value: {}", v);
}
```
will not work, and produce the trait-related error message
```
error[E0599]: no method named `sample` found for type `statrs::distribution::normal::Normal` in the current scope
 --> src\main.rs:9:15
  |
9 |     let v = n.sample(rng);
  |               ^^^^^^
  |
  = note: the method `sample` exists but the following trait bounds were not satisfied:
          `statrs::distribution::normal::Normal : rand::Rng`
  = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
  |
1 | use rand::distributions::Distribution;
  |
```

I forked `statrs` and did a couple of commits to update the dependency. Patching the `Cargo.toml` in the above example with my fork seems to work. I'll make a pull request

**Comment by tvogt** [comment]
Second this. Rand needs to be at least 6.0 to be useable in webassembly. As it stands now, can't use statrs on the web and that's a shame.
